#accuracy: 0.6298701298701299
#hits_at_k: 1.0
#loss: 0.5971093140639268
#overall_stats: { 'avg_f1_score_macro': 0.5836309295452305,
#  'avg_f1_score_micro': 0.6298701298701299,
#  'avg_f1_score_weighted': 0.5788736618578675,

input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        preprocessing:
          width: 64
          height: 64 
          num_channels: 3
        conv_layers:
            -
                num_filters: 16
                filter_size: 2
                pool_size: 2
                dropout: true
            -
                num_filters: 32
                filter_size: 2
                pool_size: 2
                dropout: true
            -
                num_filters: 16
                filter_size: 2
                pool_size: 2
                dropout: true
        

output_features:
    -
        name: label
        type: category
        reduce_inputs: concat
        fc_layers:
            -
                fc_size: 1024
                dropout: true
            -
                fc_size: 512
                dropout: true
            -
                fc_size: 256
                dropout: true

training:
    dropout_rate: 0.35
    batch_size: 16