input_features:
    -
        name: image_path
        type: image
        encoder: stacked_cnn
        pool_stride : 2
        preprocessing:
          width: 64
          height: 64 
          num_channels: 1
        conv_layers:
            -
                num_filters: 16
                filter_size: 2
                pool_size: 2
                dropout: true
            -
                num_filters: 16
                filter_size: 2
                pool_size: 2
                dropout: true

output_features:
    -
        name: label
        type: binary
        reduce_inputs: concat
        fc_layers:
            -
                fc_size: 64
                dropout: true
            -
                fc_size: 32
                dropout: true
            -
                fc_size: 16
                dropout: true

training:
    dropout_rate: 0.35
    batch_size: 2
    epochs: 1000
    early_stop: 50
    learning_rate: 0.0001